//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannersPublicitarios
    {
        public long IDBanner { get; set; }
        public string TituloCampanha { get; set; }
        public string BannerCampanha { get; set; }
        public string LinkBanner { get; set; }
    }
}
